export const practiceBucketIdeas = [
  "Bass Chords",
  "Circle Of Fifths",
  "Ear Training",
  "Pedal Learning",
  "Daw Learning",
  "Audio Interface Learning",
  "Fretboard Learning",
  "Improvisation",
  "Intervals",
  "Modes",
  "Moveable Shapes",
  "New Songs",
  "Scales",
  "Major Scales",
  "Minor Scales",
  "Pentatonic Scales",
  "Blues Scale",
  "Slap",
  "Solo",
  "Technique",
  "Transcribing",
  "Chromatic Exercises",
  "String Crossing Exercises",
];
