export const spices = [
  {
    spices: [
      { spice: "Add a bend note 🎵" },
      { spice: "Add a slap and pop 🍾" },
      { spice: "Add an open note ♩" },
      { spice: "Trill a note ⟿" },
      { spice: "Vibrato a note" },
      { spice: "Add a harmonic" },
      { spice: "Add a pop 🍾" },
      { spice: "Play note(s) louder (accent) 📢" },
      { spice: "Play notes quiet 🤫" },
      { spice: "Add a slap" },
      { spice: "Add a slide 🛝" },
      { spice: "Begin with a slide 🛝" },
      { spice: "Add a muted note Ｘ" },
      { spice: "Play notes staccato" },
      { spice: "Add a chord" },
      { spice: "Add a double stop (two notes played at once) 🎵" },
      { spice: "Add tapped notes 🚰" },
      { spice: "Add a strum 🎸" },
      { spice: "Play long note eg at end of phrase" },
      { spice: "Play short note eg at end of phrase" },
      { spice: "Add a silence or break 🤫" },
      { spice: "Try a pick and experiment with thin vs thick" },
      { spice: "Add a chromatic note" },
      { spice: "Add a dissonant note" },
    ],
  },
];
