export const allDrones = [
  { key: "Ab Drone", drone: "./audio/drones/drone_ab.mp3" },
  { key: "A Drone", drone: "./audio/drones/drone_a.mp3" },
  { key: "A# Drone", drone: "./audio/drones/drone_asharp.mp3" },
  { key: "Bb Drone", drone: "./audio/drones/drone_bb.mp3" },
  { key: "B Drone", drone: "./audio/drones/drone_b.mp3" },
  { key: "C Drone", drone: "./audio/drones/drone_c.mp3" },
  { key: "C# Drone", drone: "./audio/drones/drone_csharp.mp3" },
  { key: "Db Drone", drone: "./audio/drones/drone_db.mp3" },
  { key: "D Drone", drone: "./audio/drones/drone_d.mp3" },
  { key: "D# Drone", drone: "./audio/drones/drone_dsharp.mp3" },
  { key: "Eb Drone", drone: "./audio/drones/drone_eb.mp3" },
  { key: "E Drone", drone: "./audio/drones/drone_e.mp3" },
  { key: "F Drone", drone: "./audio/drones/drone_f.mp3" },
  { key: "F# Drone", drone: "./audio/drones/drone_fsharp.mp3" },
  { key: "Gb Drone", drone: "./audio/drones/drone_gb.mp3" },
  { key: "G Drone", drone: "./audio/drones/drone_g.mp3" },
  { key: "G# Drone", drone: "./audio/drones/drone_gsharp.mp3" },
];
