export const songs = [
  {
    jsonfile: "bait",
    songtype: "mine",
    songname: "Bait",
    key: "Key Bm",
    link: "bminor",
  },
  {
    jsonfile: "chainofevents",
    songtype: "mine",
    songname: "Chain of Events",
    key: "Key Fm",
    link: "fminor",
  },
  {
    jsonfile: "communitysucks",
    songtype: "mine",
    songname: "Community Sucks",
    key: "Key Am",
    link: "aminor",
  },
  {
    jsonfile: "feel",
    songtype: "mine",
    songname: "Feel",
    key: "Key Dm",
    link: "dminor",
  },
  {
    jsonfile: "musingsmay",
    songtype: "mine",
    songname: "Musings for May",
    key: "Key Em",
    link: "eminor",
  },
  {
    jsonfile: "swimmingpool",
    songtype: "mine",
    songname: "Swimming Pool",
    key: "F Blues",
    link: "fret_blues",
  },
  {
    jsonfile: "toothbrush",
    songtype: "mine",
    songname: "Toothbrush",
    key: "Key Bm",
    link: "bminor",
  },
  {
    jsonfile: "tresamigos",
    songtype: "mine",
    songname: "Tres Amigos",
    key: "Key G#m",
    link: "gsharpminor",
  },
  {
    jsonfile: "trolls",
    songtype: "mine",
    songname: "Trolls Have Feelings Too",
    key: "Key Ab",
    link: "aflatmajor",
  },
];
