export const songs = [
  {
    jsonfile: "alleyez",
    songtype: "transcribe",
    songname: "All Eyez On Me - 2Pac",
    key: "Key C#",
  },
  {
    jsonfile: "brokendreams",
    songtype: "transcribe",
    songname: "Broken Dreams - Thin Lizzy",
    key: "Key C",
  },
  {
    jsonfile: "cantcme",
    songtype: "transcribe",
    songname: "Can't C Me - 2Pac",
    key: "Key Am",
  },
  {
    jsonfile: "checkyoself",
    songtype: "transcribe",
    songname: "Check Yo Self - Ice Cube",
    key: "Key G",
  },
  {
    jsonfile: "climbingupthewalls",
    songtype: "transcribe",
    songname: "Climbing Up the Walls - Radiohead",
    key: "Key Bm",
  },
  {
    jsonfile: "diamondring",
    songtype: "transcribe",
    songname: "Diamond Ring - Bon Jovi",
    key: "Key Am",
  },
  {
    jsonfile: "gangsta",
    songtype: "transcribe",
    songname: "Gangsta Luv - Snoop Dogg ft The Dream",
    key: "Key Am",
  },
  {
    jsonfile: "itwasagoodday",
    songtype: "transcribe",
    songname: "It Was A Good Day - Ice Cube",
    key: "Key G",
  },
  {
    jsonfile: "juicy",
    songtype: "transcribe",
    songname: "Juicy - Notorious BIG",
    key: "Key E",
  },
  {
    jsonfile: "justify",
    songtype: "transcribe",
    songname: "Justify My Love - Madonna",
    key: "Key F#",
  },
  {
    jsonfile: "letmeride",
    songtype: "transcribe",
    songname: "Let Me Ride - Dr Dre",
    key: "Key C#",
  },
  {
    jsonfile: "oceancruiser",
    songtype: "transcribe",
    songname: "Ocean Cruiser - DJ Maretimo",
    key: "Key Cm",
  },
  {
    jsonfile: "ohme",
    songtype: "transcribe",
    songname: "Oh Me - Nirvana",
    key: "Key D#m",
  },
  {
    jsonfile: "onlygodcan",
    songtype: "transcribe",
    songname: "Only God Can Judge Me riff - 2Pac",
    key: "Key F#m",
  },
  {
    jsonfile: "mario",
    songtype: "transcribe",
    songname: "Supermario Theme Tune - Nintendo",
    key: "Key Em",
  },
  {
    jsonfile: "sandm",
    songtype: "transcribe",
    songname: "S & M - Thin Lizzy",
    key: "Key G",
  },
  {
    jsonfile: "superstar",
    songtype: "transcribe",
    songname: "Superstar Intro - The Carpenters",
    key: "Key Ab#",
  },
  {
    jsonfile: "masterplan",
    songtype: "transcribe",
    songname: "The Masterplan Intro - Oasis",
    key: "Key Am",
  },
];
