export const songs = [
  {
    jsonfile: "alleyez",
    songtype: "transcribe",
    songname: "All Eyez On Me - 2Pac",
    key: "Key C#",
  },
  {
    jsonfile: "brokendreams",
    songtype: "transcribe",
    songname: "Broken Dreams - Thin Lizzy",
    key: "Key C",
    link: "cmajor",
  },
  {
    jsonfile: "cantcme",
    songtype: "transcribe",
    songname: "Can't C Me - 2Pac",
    key: "Key Am",
    link: "aminor",
  },
  {
    jsonfile: "checkyoself",
    songtype: "transcribe",
    songname: "Check Yo Self - Ice Cube",
    key: "Key G",
    link: "gmajor",
  },
  {
    jsonfile: "climbingupthewalls",
    songtype: "transcribe",
    songname: "Climbing Up the Walls - Radiohead",
    key: "Key Bm",
    link: "bminor",
  },
  {
    jsonfile: "diamondring",
    songtype: "transcribe",
    songname: "Diamond Ring - Bon Jovi",
    key: "Key Am",
    link: "aminor",
  },
  {
    jsonfile: "gangsta",
    songtype: "transcribe",
    songname: "Gangsta Luv - Snoop Dogg ft The Dream",
    key: "Key Am",
    link: "aminor",
  },
  {
    jsonfile: "itwasagoodday",
    songtype: "transcribe",
    songname: "It Was A Good Day - Ice Cube",
    key: "Key G",
    link: "gmajor",
  },
  {
    jsonfile: "juicy",
    songtype: "transcribe",
    songname: "Juicy - Notorious BIG",
    key: "Key E",
    link: "emajor",
  },
  {
    jsonfile: "justify",
    songtype: "transcribe",
    songname: "Justify My Love - Madonna",
    key: "Key F#",
    link: "fsharpmajor",
  },
  {
    jsonfile: "letmeride",
    songtype: "transcribe",
    songname: "Let Me Ride - Dr Dre",
    key: "Key C#",
  },
  {
    jsonfile: "oceancruiser",
    songtype: "transcribe",
    songname: "Ocean Cruiser - DJ Maretimo",
    key: "Key Cm",
    link: "cminor",
  },
  {
    jsonfile: "ohme",
    songtype: "transcribe",
    songname: "Oh Me - Nirvana",
    key: "Key D#m",
    link: "dsharpminor",
  },
  {
    jsonfile: "onlygodcan",
    songtype: "transcribe",
    songname: "Only God Can Judge Me riff - 2Pac",
    key: "Key F#m",
    link: "fsharpminor",
  },
  {
    jsonfile: "mario",
    songtype: "transcribe",
    songname: "Supermario Theme Tune - Nintendo",
    key: "Key Em",
    link: "eminor",
  },
  {
    jsonfile: "sandm",
    songtype: "transcribe",
    songname: "S & M - Thin Lizzy",
    key: "Key G",
    link: "gmajor",
  },
  {
    jsonfile: "superstar",
    songtype: "transcribe",
    songname: "Superstar Intro - The Carpenters",
    key: "Key Ab",
    link: "aflatmajor",
  },
  {
    jsonfile: "masterplan",
    songtype: "transcribe",
    songname: "The Masterplan Intro - Oasis",
    key: "Key Am",
    link: "aminor",
  },
];
