export const allKeys = [
  {
    keys: [
      { key: "Cb Major" },
      { key: "Gb Major", link: "gflatmajor" },
      { key: "Db Major", link: "dflatmajor" },
      { key: "Ab Major", link: "aflatmajor" },
      { key: "Eb Major", link: "eflatmajor" },
      { key: "Bb Major", link: "bflatmajor" },
      { key: "F Major", link: "fmajor" },
      { key: "C Major", link: "cmajor" },
      { key: "G Major", link: "gmajor" },
      { key: "D Major", link: "dmajor" },
      { key: "A Major", link: "amajor" },
      { key: "E Major", link: "emajor" },
      { key: "B Major", link: "bmajor" },
      { key: "F# Major", link: "fsharpmajor" },
      { key: "C# Major", link: "csharpmajor" },
      { key: "Ab Minor" },
      { key: "Eb Minor", link: "eflatminor" },
      { key: "Bb Minor", link: "bflatminor" },
      { key: "Fm", link: "fminor" },
      { key: "Cm", link: "cminor" },
      { key: "Gm", link: "gminor" },
      { key: "Dm", link: "dminor" },
      { key: "Am", link: "aminor" },
      { key: "Em", link: "eminor" },
      { key: "Bm", link: "bminor" },
      { key: "F#m", link: "fsharpminor" },
      { key: "C#m", link: "csharpminor" },
      { key: "G#m", link: "gsharpminor" },
      { key: "D#m", link: "dsharpminor" },
      { key: "A#m", link: "asharpminor" },
    ],
  },
];
